### ISSUE TITLE
Issue regard Connet

### ISSUE THREAD

**Issue by sunilinfo02** [craigwatson/dvsa-test-check#4]
Hi

I am also try to check cancel date. But when i fill the detail and try to connect then it return error.
Script not connect.
Can you help on this.

Regards
Sunil

**Comment by sunilinfo02** [comment]
Hi

Any update?

**Comment by craigwatson** [comment]
Hi Sunil,

Really sorry for missing this - for some reason I didn't get any email notifications of opened GitHub issues.

Unfortunately the script needs "live" credentials in order to work, so as I passed my test three years ago, I'm unable to verify that the script works - this is covered in the README document [here](https://github.com/craigwatson/dvsa-test-check#dvsa-site-changes).

What output does the script give you?

Thanks,
Craig

**Comment by venkatgb** [comment]
Hello Craig, Firstly many thanks for creating this code to check test cancellations. Much Appreciated.
I am not a php expert but managed to run the code successfully with live credentials :). But it does not retrieve the earlier dates although it is available when I manually check the website. There are no errors in the log. I had a doubt if 'ideal_day'      => 'SAT' in the secret file is trying to pull only the availability on that day but it doesn't seem to be the case as even if I set it to the available day, it still doesn't retrieve the availability. 

Snippet from the log:
2019-12-10 10:04:42 -- INFO : Requesting https://driverpracticaltest.dvsa.gov.uk
2019-12-10 10:04:42 -- INFO : ... Sending csrftoken: ''
2019-12-10 10:04:42 -- INFO : ... Sending testChoice: 'ASAP'
2019-12-10 10:04:42 -- INFO : ... Sending preferredTestDate: '10%2F12%2F2019'
2019-12-10 10:04:42 -- INFO : ... Sending drivingLicenceSubmit: 'Continue'
2019-12-10 10:04:42 -- INFO : ... Got HTTP 403
2019-12-10 10:04:42 -- INFO : ... Sleeping for 2 seconds
2019-12-10 10:04:44 -- INFO : Clearing cookies from ./dvsa_<<licenceNumber>>_cookies.txt
2019-12-10 10:04:44 -- WARN : No dates found

There were a number of availabilities on 04-Jan-2020. 
I think I got a clue from the response code (403) that the request is forbidden for some reason.
Just wanted to bring it to your attention if you can see what the issue is as it might help others :)

Kind Regards
Venkat

**Comment by craigwatson** [comment]
Hi @venkatgb - the 403 code is indeed HTTP forbidden. As far as I'm aware, the script currently doesn't work as the DVLA have implemented a bot/DDoS protection layer - I don't currently have the skills or the time to work around this.
