### ISSUE TITLE
HTTP 403 - Theory Test Number

### ISSUE THREAD

**Issue by ralphdt** [craigwatson/dvsa-test-check#5]
2020-10-15 15:07:45 -- INFO : ========= Running Check for: person
2020-10-15 15:07:45 -- INFO : Requesting https://driverpracticaltest.dvsa.gov.uk/login
2020-10-15 15:07:45 -- INFO : ... Got HTTP 403
2020-10-15 15:07:45 -- INFO : ... Sleeping for 2 seconds

Using a Theory Test Number. Is the login URL correct ?

**Comment by craigwatson** [comment]
Hi @ralphdt,

As far as I'm aware, the Login URL is correct (the URL presents a login form). However I'm aware of various changes that have been made to the DVSA website since the script was first written, including bot/script detection and prevention.

It may well be that the script has been rendered unusable due to these changes.

Thanks,
Craig

**Comment by ralphdt** [comment]
https://driverpracticaltest.dvsa.gov.uk/login?passwordType=ALTERNATIVE

no worries. i think the problem is using the theory test number instead of application number.
